export const SET_GLOBAL_STATE = 'SET_GLOBAL_STATE';
export const SET_SLIDES_STATE = 'SET_SLIDES_STATE';
export const SET_PLANS_STATE = 'SET_PLANS_STATE';

export const SET_ACTIVE_PLAN_ID = 'SET_ACTIVE_PLAN_ID';
export const GET_ACTIVE_PLAN_MSG = 'GET_ACTIVE_PLAN_MSG';
